default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  database: zenlife_db
  username: zenlife_db_user
  password: <%= ENV['DATABASE_PASSWORD'] %>
