default: &default
  adapter: sqlite3
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  url: postgresql://postgres:df1YcjJ7J0rSu2Z0JwWu@containers-us-west-43.railway.app:6342/railway
  database: railway
  username: postgres
  password: df1YcjJ7J0rSu2Z0JwWu
